### ISSUE TITLE
怎么划分？

### ISSUE THREAD

**Issue by ForgetAll** [AndroidDevelopers-FirstSquad/Development-Solutions#1]
啥划分？项目吗？建议MVP啊……

**Comment by fanKarl** [comment]
MVP+RxJava+ButterKnife+Retrofit，这么玩怎么样？会不会把自己玩死啊。。。

**Comment by ForgetAll** [comment]
玩死拉倒啊，玩的项目就应该把自己往死里玩啊

**Comment by fanKarl** [comment]
可以可以，那就这么玩，快加入我的黄焖菜鸟战队开刷吧

**Comment by ForgetAll** [comment]
突然想起来  Retrofit自己完全没玩过啊，真会玩死啊

**Comment by fanKarl** [comment]
我一个都没玩过，已经预见到未来了
